prueba/Controllers/PrincipalPageController.cs
using Microsoft.AspNetCore.Mvc;
using prueba.Models;

namespace prueba.Controllers
{
    public class PrincipalPageController : Controller
    {
        private readonly trabajosDbContext _context;

        public PrincipalPageController(trabajosDbContext context)
        {
            _context = context;
        }


        // GET: PrincipalPage
        public IActionResult Index()
        {

            var count = (from x in _context.empresa select x.empresaID).Count();

            var count2 = (from x in _context.ofertas select x.ofertaID).Count();

            var empresa = (from m in _context.ofertas
                           select m).ToList()
                           .OrderByDescending(m => m.ofertaID).Take(3);

            var testimonios = (from n in _context.testimonios
                               select n).ToList();

            ViewData["contar"] = count;
            ViewData["contarPlazas"] = count2;
            ViewData["testimonios"] = testimonios;
            ViewData["empresa"] = empresa;
            return View();


        }


    }
}

prueba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prueba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/prueba.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-custom border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PrincipalPage" asp-action="Index">PIWI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Orientacion" asp-action="Index">Orientacion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="empleoController1" asp-action="Index">Empleos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - prueba - <a asp-area="" asp-controller="Home" asp-action="Login">P</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>